# Generated by Django 5.0.4 on 2024-06-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('institute_name', models.CharField(max_length=100)),
            ],
        ),
    ]
