# Generated by Django 4.2.14 on 2024-09-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_due',
            field=models.BooleanField(default=False),
        ),
    ]
