# Generated by Django 5.0.4 on 2024-05-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='student_affidavit',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='student_affidevit',
            field=models.FileField(blank=True, null=True, upload_to='images/students/affidevit/'),
        ),
        migrations.AlterField(
            model_name='marksheets',
            name='student_enrollment_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='student_enrollment_no',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
