# Generated by Django 5.0.4 on 2024-05-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='student_admit_card',
            field=models.FileField(blank=True, null=True, upload_to='images/students/admit_card/'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='student_affidevit',
            field=models.FileField(blank=True, null=True, upload_to='images/students/affidevit/'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='student_migrations',
            field=models.FileField(blank=True, null=True, upload_to='images/students/migrations/'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='student_provision',
            field=models.FileField(blank=True, null=True, upload_to='images/students/provision/'),
        ),
    ]
