# Generated by Django 5.0.4 on 2024-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0002_remove_studentdata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='student_degree',
            field=models.FileField(blank=True, null=True, upload_to='images/students/degree/'),
        ),
    ]
