# Generated by Django 5.0.4 on 2024-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapp', '0003_adminlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='contact_no',
            field=models.CharField(default='User Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='email',
            field=models.EmailField(default=8099987, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='full_name',
            field=models.CharField(default='panwara925@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
